apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: zfs-node
  name: system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zfs-node
  namespace: system
  labels:
    control-plane: zfs-node
spec:
  selector:
    matchLabels:
      control-plane: zfs-node
  template:
    metadata:
      labels:
        control-plane: zfs-node
    spec:
      nodeSelector:
        zfs.unstable.cloud/storage: ""
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: zfs-node
      containers:
      - command:
        - /zfs-operator
        args:
        - --enable-leader-election
        - --node-name=$(NODE_NAME)
        image: controller:latest
        name: agent
        securityContext:
          privileged: true
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        resources:
          # limits:
          #   cpu: 100m
          #   memory: 30Mi
          requests:
            cpu: 100m
            memory: 30Mi
        volumeMounts:
        - name: dev
          mountPath: /dev
      terminationGracePeriodSeconds: 300
      volumes:
      - name: dev
        hostPath:
          path: /dev
