apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: zfs-node
  name: zfs-node-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: zfs-node
