name: envtest

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:

    -
      # https://github.com/actions/checkout
      name: Checkout
      uses: actions/checkout@v2

    -
      name: UnitTest
      run: |
        sudo apt-get update
        sudo apt-get install -y zfsutils-linux
        sudo truncate -s 2G /disk.img
        sudo zpool create tank /disk.img
        sudo zfs create tank/envtest

        PATH=$PATH:/usr/local/go/bin:/usr/local/kubebuilder/bin

        os=$(go env GOOS)
        arch=$(go env GOARCH)
        curl -L https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp
        sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder

        sudo go test -v ./tests/...
